default_movement_speed = 2.0
bar_height = 0  # If 0 then removed
default_tank_x = 50
window_height = 600
window_width = 800
background_scale = 50
object_collision_damage = 0.5
object_collision_cooldown = 0.5
hp_bar_width = 50
hp_bar_height = 5
hp_bar_y_offset = -25
